[workspace]
resolver = "2"
members = [
    "async-part1",
    "async-part2",
    "async-part3",
    "async-part4",
    "async-part5",
    "async-part6",
]

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"
overflow-checks = false