[package]
name = "async-part2"
version = "0.1.0"
edition = "2021"

[features]
#default = []
sync = []
coroutines = []
coroutines_trait = []

[dependencies]
futures = "0.3.30"
tokio = {version="1.39.3", features=["full"]}
clap = { version = "3.0", features = ["derive"] }
