[package]
name = "async-part3"
version = "0.1.0"
edition = "2021"

[dependencies]
pin-project = "1.0"
tokio = {version="1.39.3", features=["full"]}
env_logger = "0.11.5"
log = "0.4.22"
futures = "0.3"

